# Trabajo Practico 4

## Parte 1

In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [6]:
# Importamos la base de datos.
df_original_hog = pd.read_excel(r'usu_hogar_T123.xlsx')

# Importamos la tabla de la encuesta individual.
df_original_ind = pd.read_excel(r'usu_individual_T123.xlsx')

In [7]:
# Nos quedamos con los datos correspondientes a los aglomerados de Ciudad Autónoma de Buenos Aires y Gran Buenos Aires.
df_hog = df_original_hog[(df_original_hog['AGLOMERADO'] == 32) | (df_original_hog['AGLOMERADO'] == 33)]

# Para esta encuesta también nos quedamos con los datos correspondientes a los aglomerados de Ciudad Autónoma de Buenos Aires y Gran Buenos Aires.
df_ind = df_original_ind[(df_original_ind['AGLOMERADO'] == 32) | (df_original_ind['AGLOMERADO'] == 33)]

In [87]:
# Unimos las tablas a partir de la columna CODUSU, que refiere al número de identificación del registro y que permite relacionar a las viviendas con los hogares y las personas.
df = df_hog.merge(df_ind, on=['CODUSU', 'NRO_HOGAR'], how='outer')

In [88]:
# Primer paso:

types = []

for columna in df.columns:
    if df[columna].dtypes not in types:
        types.append(df[columna].dtypes)
        
print('Formatos de las variables:', types)

nums = ['float64','int64']
listado = []

for columna in df.columns:
    if df[columna].dtypes in nums:
        listado.append(columna)

print('Listado de variables que corregiremos:', listado)

# Segundo paso:

print('\nShape de la base de CABA y GBA: ', df.shape)

for i in listado:
    df = df[((df[[i]] >= 0) | (df[[i]].isna())).all(1)]

df

Formatos de las variables: [dtype('O'), dtype('int64'), dtype('float64')]
Listado de variables que corregiremos: ['ANO4_x', 'TRIMESTRE_x', 'NRO_HOGAR', 'REALIZADA', 'REGION_x', 'AGLOMERADO_x', 'PONDERA_x', 'IV1', 'IV2', 'IV3', 'IV4', 'IV5', 'IV6', 'IV7', 'IV8', 'IV9', 'IV10', 'IV11', 'IV12_1', 'IV12_2', 'IV12_3', 'II1', 'II2', 'II3', 'II3_1', 'II4_1', 'II4_2', 'II4_3', 'II5', 'II5_1', 'II6', 'II6_1', 'II7', 'II8', 'II9', 'V1', 'V2', 'V21', 'V22', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19_A', 'V19_B', 'IX_TOT', 'IX_MEN10', 'IX_MAYEQ10', 'ITF_x', 'DECIFR_x', 'IDECIFR_x', 'RDECIFR_x', 'GDECIFR_x', 'PDECIFR_x', 'ADECIFR_x', 'IPCF_x', 'DECCFR_x', 'IDECCFR_x', 'RDECCFR_x', 'GDECCFR_x', 'PDECCFR_x', 'ADECCFR_x', 'PONDIH_x', 'VII1_1', 'VII1_2', 'VII2_1', 'VII2_2', 'VII2_3', 'VII2_4', 'ANO4_y', 'TRIMESTRE_y', 'COMPONENTE', 'H15', 'REGION_y', 'AGLOMERADO_y', 'PONDERA_y', 'CH03', 'CH04', 'CH06', 'CH07', 'CH08', 'CH09', 'CH10', 'CH11', 'CH12', 'CH13', 'CH14', 'CH15', 'CH15_COD', 'CH16', 'CH16_COD', 'NIVEL_ED', 'ESTADO', 'CAT_OCUP', 'CAT_INAC', 'IMPUTA', 'PP02C1', 'PP02C2', 'PP02C3', 'PP02C4', 'PP02C5', 'PP02C6', 'PP02C7', 'PP02C8', 'PP02E', 'PP02H', 'PP02I', 'PP03C', 'PP03D', 'PP3E_TOT', 'PP3F_TOT', 'PP03G', 'PP03H', 'PP03I', 'PP03J', 'INTENSI', 'PP04A', 'PP04B_COD', 'PP04B1', 'PP04B2', 'PP04B3_MES', 'PP04B3_ANO', 'PP04B3_DIA', 'PP04C', 'PP04C99', 'PP04D_COD', 'PP04G', 'PP05B2_MES', 'PP05B2_ANO', 'PP05B2_DIA', 'PP05C_1', 'PP05C_2', 'PP05C_3', 'PP05E', 'PP05F', 'PP05H', 'PP06A', 'PP06C', 'PP06D', 'PP06E', 'PP06H', 'PP07A', 'PP07C', 'PP07D', 'PP07E', 'PP07F1', 'PP07F2', 'PP07F3', 'PP07F4', 'PP07F5', 'PP07G1', 'PP07G2', 'PP07G3', 'PP07G4', 'PP07G_59', 'PP07H', 'PP07I', 'PP07J', 'PP07K', 'PP08D1', 'PP08D4', 'PP08F1', 'PP08F2', 'PP08J1', 'PP08J2', 'PP08J3', 'PP09A', 'PP09B', 'PP09C', 'PP10A', 'PP10C', 'PP10D', 'PP10E', 'PP11A', 'PP11B_COD', 'PP11B1', 'PP11B2_MES', 'PP11B2_ANO', 'PP11B2_DIA', 'PP11C', 'PP11C99', 'PP11D_COD', 'PP11G_ANO', 'PP11G_MES', 'PP11G_DIA', 'PP11L', 'PP11L1', 'PP11M', 'PP11N', 'PP11O', 'PP11P', 'PP11Q', 'PP11R', 'PP11S', 'PP11T', 'P21', 'DECOCUR', 'IDECOCUR', 'RDECOCUR', 'GDECOCUR', 'PDECOCUR', 'ADECOCUR', 'PONDIIO', 'TOT_P12', 'P47T', 'DECINDR', 'IDECINDR', 'RDECINDR', 'GDECINDR', 'PDECINDR', 'ADECINDR', 'PONDII', 'V2_M', 'V3_M', 'V4_M', 'V5_M', 'V8_M', 'V9_M', 'V10_M', 'V11_M', 'V12_M', 'V18_M', 'V19_AM', 'V21_M', 'T_VI', 'ITF_y', 'DECIFR_y', 'IDECIFR_y', 'RDECIFR_y', 'GDECIFR_y', 'PDECIFR_y', 'ADECIFR_y', 'IPCF_y', 'DECCFR_y', 'IDECCFR_y', 'RDECCFR_y', 'GDECCFR_y', 'PDECCFR_y', 'ADECCFR_y', 'PONDIH_y']

Shape de la base de CABA y GBA:  (7619, 263)

,CODUSU,ANO4_x,TRIMESTRE_x,NRO_HOGAR,REALIZADA,REGION_x,MAS_500_x,AGLOMERADO_x,PONDERA_x,IV1,...,PDECIFR_y,ADECIFR_y,IPCF_y,DECCFR_y,IDECCFR_y,RDECCFR_y,GDECCFR_y,PDECCFR_y,ADECCFR_y,PONDIH_y
1,TQRMNORVYHMOTSCDEIJAH00802517,2023,1,1,1,1,S,33,1066,1,...,NaN,12,0.0,12,NaN,12,12.0,NaN,12,0
3,TQRMNOSQRHLLTTCDEIJAH00719390,2023,1,1,1,1,S,33,2270,2,...,NaN,5,79000.0,6,NaN,6,6.0,NaN,7,4733
4,TQSMNOSQRHLLTTCDEIJAH00719389,2023,1,1,1,1,S,33,2161,1,...,NaN,3,96000.0,7,NaN,7,7.0,NaN,8,2672
5,TQRMNORTUHKOQQCDEIJAH00780489,2023,1,1,1,1,S,33,3097,1,...,NaN,4,125000.0,8,NaN,8,8.0,NaN,9,4844
6,TQRMNOUTRHKNQMCDEIJAH00802590,2023,1,1,1,1,S,33,2571,1,...,NaN,4,120000.0,8,NaN,8,8.0,NaN,9,3482
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7614,TQRMNOSSQHKOOMCDEIJAH00802644,2023,1,1,1,1,S,33,3381,1,...,NaN,1,14750.0,1,NaN,1,1.0,NaN,1,4548
7615,TQRMNOSSQHKOOMCDEIJAH00802644,2023,1,1,1,1,S,33,3381,1,...,NaN,1,14750.0,1,NaN,1,1.0,NaN,1,4548
7616,TQRMNOSSQHKOOMCDEIJAH00802644,2023,1,1,1,1,S,33,3381,1,...,NaN,1,14750.0,1,NaN,1,1.0,NaN,1,4548
7617,TQRMNORYPHJKNPCDEIJAH00794297,2023,1,1,1,1,S,33,521,1,...,NaN,1,32000.0,2,NaN,2,2.0,NaN,2,896
7618,TQRMNORYPHJKNPCDEIJAH00794297,2023,1,1,1,1,S,33,521,1,...,NaN,1,32000.0,2,NaN,2,2.0,NaN,2,896

In [91]:
def df_without_decilvariables(df):
    decil_list = variables_to_remove = ["DECIFR_x", "IDECIFR_x", "RDECIFR_x", "GDECIFR_x", "PDECIFR_x", "ADECIFR_x","DECCFR_x", "IDECCFR_x", "RDECCFR_x", "GDECCFR_x", "PDECCFR_x", "ADECCFR_x","DECOCUR", "IDECOCUR", "RDECOCUR", "GDECOCUR", "PDECOCUR", "ADECOCUR","DECINDR", "IDECINDR", "RDECINDR", "GDECINDR", "PDECINDR", "ADECINDR", "DECIFR_y", "IDECIFR_y", "RDECIFR_y", "GDECIFR_y", "PDECIFR_y", "ADECIFR_y","DECCFR_y", "IDECCFR_y", "RDECCFR_y", "GDECCFR_y", "PDECCFR_y", "ADECCFR_y"]
    for var in decil_list:
        if var in df.columns:
            df = df.drop(var, axis=1)
    
    return df

In [92]:
# Chequeamos los missing values de las variables para decidir cuáles mantenemos.

df = df_without_decilvariables(df)

missings = df.isna().sum().sort_values(ascending=False)
pd.set_option('display.max_rows', None)
print(missings)

PP09C_ESP       5944
IV1_ESP         5934
IV3_ESP         5934
IV7_ESP         5932
PP09A_ESP       5930
IMPUTA          5920
II7_ESP         5920
CH16_COD        5859
II8_ESP         5770
PP11D_COD       5755
PP11O           5680
PP11C           5680
PP11L1          5680
PP11L           5680
PP11G_DIA       5680
PP11G_MES       5680
PP11G_ANO       5680
PP11C99         5680
PP11B2_DIA      5680
PP11N           5680
PP11B2_ANO      5680
PP11B2_MES      5680
PP11B1          5680
PP11B_COD       5680
PP11A           5680
PP10E           5680
PP10D           5680
PP10C           5680
PP10A           5680
PP11M           5680
PP11R           5680
PP11Q           5680
PP11S           5680
PP11T           5680
PP11P           5680
CH15_COD        4892
PP06E           3728
PP05E           3728
PP06D           3728
PP07A           3728
PP06C           3728
PP06A           3728
PP07C           3728
PP05H           3728
PP05F           3728
PP07E           3728
PP05C_3         3728
PP07D           3728
PP05C_2         3728
PP05C_1         3728
PP05B2_DIA      3728
PP07F1          3728
PP05B2_ANO      3728
PP06H           3728
PP08J1          3728
PP05B2_MES      3728
PP04B_COD       3728
PP3E_TOT        3728
PP03D           3728
PP03C           3728
PP03H           3728
PP03I           3728
PP03J           3728
INTENSI         3728
PP04A           3728
PP04B1          3728
PP07F3          3728
PP04B2          3728
PP04B3_MES      3728
PP04B3_ANO      3728
PP04B3_DIA      3728
PP04C           3728
PP04C99         3728
PP04D_COD       3728
PP04G           3728
PP07F2          3728
PP3F_TOT        3728
PP07F4          3728
PP08D1          3728
PP07F5          3728
PP09B           3728
PP09A           3728
PP08J3          3728
PP08J2          3728
PP03G           3728
PP08F2          3728
PP08F1          3728
PP08D4          3728
PP09C           3728
PP07K           3728
PP07J           3728
PP07I           3728
PP07H           3728
PP07G_59        3728
PP07G4          3728
PP07G3          3728
PP07G2          3728
PP07G1          3728
CH14            2767
P47T              23
V12_M              0
V18_M              0
V19_AM             0
IPCF_y             0
V21_M              0
T_VI               0
ITF_y              0
V10_M              0
V11_M              0
V2_M               0
V9_M               0
V8_M               0
V5_M               0
V4_M               0
V3_M               0
PONDII             0
TOT_P12            0
PONDIIO            0
P21                0
CODUSU             0
PP02E              0
PP02I              0
II4_1              0
II4_3              0
II5                0
II5_1              0
II6                0
II6_1              0
II7                0
II8                0
II9                0
V1                 0
V2                 0
V21                0
V22                0
V3                 0
V4                 0
V5                 0
V6                 0
V7                 0
V8                 0
V9                 0
V10                0
V11                0
V12                0
V13                0
II4_2              0
II3_1              0
PP02H              0
II3                0
TRIMESTRE_x        0
NRO_HOGAR          0
REALIZADA          0
REGION_x           0
MAS_500_x          0
AGLOMERADO_x       0
PONDERA_x          0
IV1                0
IV2                0
IV3                0
IV4                0
IV5                0
IV6                0
IV7                0
IV8                0
IV9                0
IV10               0
IV11               0
IV12_1             0
IV12_2             0
IV12_3             0
II1                0
II2                0
V14                0
V15                0
V16                0
V17                0
CH06               0
CH07               0
CH08               0
CH09               0
CH10               0
CH11               0
CH12               0
CH13               0
CH15               0
CH16               0
NIVEL_ED           0
ESTADO             0
CAT_OCUP           0
CAT_INAC           0
PP02C1             0
PP02C2             0
PP02C3             0
PP02C4             0
PP02C5             0
PP02C6             0
PP02C7             0
PP02C8             0
ANO4_x             0
CH05               0
CH04               0
CH03               0
VII1_2             0
V18                0
V19_A              0
V19_B              0
IX_TOT             0
IX_MEN10           0
IX_MAYEQ10         0
ITF_x              0
IPCF_x             0
PONDIH_x           0
VII1_1             0
VII2_1             0
PONDERA_y          0
VII2_2             0
VII2_3             0
VII2_4             0
ANO4_y             0
TRIMESTRE_y        0
COMPONENTE         0
H15                0
REGION_y           0
MAS_500_y          0
AGLOMERADO_y       0
PONDIH_y           0
dtype: int64

In [93]:
# Procedemos a crear una función que nos devuelva nuestro Data Frame sin columnas con missing values.

def df_without_missings(df):
    
    pd.set_option('display.max_rows', 10)
    varwithoutmissings = []
    
    missing_values = df.isna().sum()
    missing_values = missing_values.reset_index().rename(columns={'index': 'Variable', 0:'Missings'})
    
    for i in range(0, len(missing_values)):
        if missing_values['Missings'][i] < 2800:
            varwithoutmissings.append(missing_values['Variable'][i])

    print('Cantidad de variables con missings:', (len(df.columns)-len(varwithoutmissings)))
    
    dftest = df[varwithoutmissings]
    
    print('\nShape del viejo Data Frame:', df.shape)
    
    print('\nShape del nuevo Data Frame:', dftest.shape)
    
    return dftest

In [94]:
# Ahora creamos una función que nos devuelva nuestro Data Frame sin columnas duplicadas. A partir del merge de dos Data Frames, hay variables que pueden duplicarse y que, por lo tanto, no aportan información adicional. Procederemos a generar una función que permita eliminar estas columnas del df.

def clean_duplicates(df):
    
    df_original = df.copy()
    df = df.T.drop_duplicates().T

    print('Cantidad de variables duplicadas:', (len(df_original.columns)-len(df.columns)))
    print('\nLista de variables duplicadas:')
          
    for i in range(0,len(df_original.columns)):
        if df_original.columns[i] not in df.columns:
            print(df_original.columns[i])
          
    print('\nShape del nuevo Data Frame:', df.shape)
        
    return df

In [95]:
df = df_without_missings(df)
df = clean_duplicates(df)

Cantidad de variables con missings: 98

Shape del viejo Data Frame: (5944, 227)

Shape del nuevo Data Frame: (5944, 129)
Cantidad de variables duplicadas: 12

Lista de variables duplicadas:
REALIZADA
REGION_x
V19_B
ANO4_y
TRIMESTRE_y
REGION_y
MAS_500_y
AGLOMERADO_y
PONDERA_y
ITF_y
IPCF_y
PONDIH_y

Shape del nuevo Data Frame: (5944, 117)

In [96]:
valores_m = [.35,.37,.46,.51,.55,.6,.64,.66,.68,.69,.7,.72,.74,.76,.76,.77,.77,.77,.76,.77,.76,.67,.63]
valores_h = [.35,.37,.46,.51,.55,.6,.64,.66,.68,.69,.79,.82,.85,.9,.96,1,1.03,1.04,1.02,1,1,.83,.74]
df['adulto_equiv'] = 0

In [98]:
modified_rows = []

for j in range(0, 5944, 1):
    row = df.iloc[j].copy()
    if row['CH04'] == 2:
        for i in range(0, 18):
            if row['CH06'] == i:
                row['adulto_equiv'] = valores_m[i]
        if row['CH06'] in range(18,30):
            row['adulto_equiv'] = valores_m[18]
        elif row['CH06'] in range(30,46):
            row['adulto_equiv'] = valores_m[19]
        elif row['CH06'] in range(46,61):
            row['adulto_equiv'] = valores_m[20]
        elif row['CH06'] in range(61,76):
            row['adulto_equiv'] = valores_m[21]
        elif row['CH06'] in range(76,99):
            row['adulto_equiv'] = valores_m[22]
    
    else:
        for i in range(0,18,1):
            if row['CH06'] == i:
                row['adulto_equiv'] = valores_h[i]
        if row['CH06'] in range(18,30):
            row['adulto_equiv'] = valores_h[18]
        elif row['CH06'] in range(30,46):
            row['adulto_equiv'] = valores_h[19]
        elif row['CH06'] in range(46,61):
            row['adulto_equiv'] = valores_h[20]
        elif row['CH06'] in range(61,76):
            row['adulto_equiv'] = valores_h[21]
        elif row['CH06'] in range(76,100):
            row['adulto_equiv'] = valores_h[22]
    modified_rows.append(row)

df = pd.DataFrame(modified_rows)
df

,CODUSU,ANO4_x,TRIMESTRE_x,NRO_HOGAR,MAS_500_x,AGLOMERADO_x,PONDERA_x,IV1,IV2,IV3,...,V8_M,V9_M,V10_M,V11_M,V12_M,V18_M,V19_AM,V21_M,T_VI,adulto_equiv
1,TQRMNORVYHMOTSCDEIJAH00802517,2023,1,1,S,33,1066,1,4,1,...,0,0,0,0,0,0,0,0,0,0.76
3,TQRMNOSQRHLLTTCDEIJAH00719390,2023,1,1,S,33,2270,2,4,1,...,0,0,0,0,0,0,0,0,0,0.77
4,TQSMNOSQRHLLTTCDEIJAH00719389,2023,1,1,S,33,2161,1,3,1,...,0,0,0,0,0,0,0,0,96000,0.63
5,TQRMNORTUHKOQQCDEIJAH00780489,2023,1,1,S,33,3097,1,3,1,...,0,0,0,0,0,0,0,40000,125000,0.63
6,TQRMNOUTRHKNQMCDEIJAH00802590,2023,1,1,S,33,2571,1,2,1,...,0,0,0,0,0,0,0,0,0,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7614,TQRMNOSSQHKOOMCDEIJAH00802644,2023,1,1,S,33,3381,1,3,1,...,0,0,0,0,0,0,0,0,0,0.76
7615,TQRMNOSSQHKOOMCDEIJAH00802644,2023,1,1,S,33,3381,1,3,1,...,0,0,0,0,0,0,0,0,0,0.76
7616,TQRMNOSSQHKOOMCDEIJAH00802644,2023,1,1,S,33,3381,1,3,1,...,0,0,0,0,0,0,0,0,0,0.66
7617,TQRMNORYPHJKNPCDEIJAH00794297,2023,1,1,S,33,521,1,3,1,...,0,0,0,0,0,0,0,0,0,0.67
7618,TQRMNORYPHJKNPCDEIJAH00794297,2023,1,1,S,33,521,1,3,1,...,0,0,0,0,0,0,0,0,0,1.02

In [94]:
df['ad_equiv_hogar'] = df.groupby('CODUSU')['adulto_equiv'].transform('sum')
df

,CODUSU,ANO4_x,TRIMESTRE_x,NRO_HOGAR_x,MAS_500_x,AGLOMERADO_x,PONDERA_x,IV1,IV2,IV3,...,GDECIFR_y,ADECIFR_y,IPCF_y,DECCFR_y,RDECCFR_y,GDECCFR_y,ADECCFR_y,PONDIH_y,adulto_equiv,ad_equiv_hogar
1,TQRMNORVYHMOTSCDEIJAH00802517,2023,1,1,S,33,1066,1,4,1,...,12.0,12,0.0,12,12,12.0,12,0,0.76,0.76
3,TQRMNOSQRHLLTTCDEIJAH00719390,2023,1,1,S,33,2270,2,4,1,...,5.0,5,79000.0,6,6,6.0,7,4733,0.77,0.77
4,TQSMNOSQRHLLTTCDEIJAH00719389,2023,1,1,S,33,2161,1,3,1,...,2.0,3,96000.0,7,7,7.0,8,2672,0.63,0.63
5,TQRMNORTUHKOQQCDEIJAH00780489,2023,1,1,S,33,3097,1,3,1,...,4.0,4,125000.0,8,8,8.0,9,4844,0.63,0.63
6,TQRMNOUTRHKNQMCDEIJAH00802590,2023,1,1,S,33,2571,1,2,1,...,3.0,4,120000.0,8,8,8.0,9,3482,1.00,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7681,TQRMNOSSQHKOOMCDEIJAH00802644,2023,1,1,S,33,3381,1,3,1,...,1.0,1,14750.0,1,1,1.0,1,4548,0.76,2.95
7682,TQRMNOSSQHKOOMCDEIJAH00802644,2023,1,1,S,33,3381,1,3,1,...,1.0,1,14750.0,1,1,1.0,1,4548,0.76,2.95
7683,TQRMNOSSQHKOOMCDEIJAH00802644,2023,1,1,S,33,3381,1,3,1,...,1.0,1,14750.0,1,1,1.0,1,4548,0.66,2.95
7684,TQRMNORYPHJKNPCDEIJAH00794297,2023,1,1,S,33,521,1,3,1,...,1.0,1,32000.0,2,2,2.0,2,896,0.67,1.69
7685,TQRMNORYPHJKNPCDEIJAH00794297,2023,1,1,S,33,521,1,3,1,...,1.0,1,32000.0,2,2,2.0,2,896,1.02,1.69

In [95]:
respondieron = df[df['ITF_x'] != 0].copy()
norespondieron = df[df['ITF_x'] == 0].copy()

print(df.shape)
print(respondieron.shape)
print(norespondieron.shape)
print('\n%.0f personas no respondieron cuál es su ingreso familiar total (ITF).' %len(norespondieron))

respondieron['ingreso_necesario'] = respondieron['ad_equiv_hogar']*57371.05

(5998, 146)
(4188, 146)
(1810, 146)

1810 personas no respondieron cuál es su ingreso familiar total (ITF).

In [96]:
respondieron['pobre'] = (respondieron['ITF_x'] < respondieron['ingreso_necesario']).astype(int)

print("Identificamos %.0f pobres." %np.sum(respondieron['pobre']))
print("Esto equivale a un %.2f por ciento de pobres de la base respondieron." %((np.sum(respondieron['pobre']/len(respondieron)))*100))

Identificamos 1590 pobres.
Esto equivale a un 37.97 por ciento de pobres de la base respondieron.

## Parte 2

In [118]:
from sklearn.metrics import (
    confusion_matrix,
    roc_curve,
    roc_auc_score,
    accuracy_score,
    mean_squared_error,
    precision_score,
)


def evalua_metodo(modelo, X_train, y_train, X_test, y_test):
    """
    Evalúa un modelo utilizando métricas como la matriz de confusión,
    las curvas ROC, el valor de AUC y el accuracy score.

    Parameters:
    - modelo: El modelo a evaluar (debe ser compatible con la interfaz de scikit-learn).
    - X_train: Datos de entrenamiento.
    - y_train: Etiquetas de entrenamiento.
    - X_test: Datos de prueba.
    - y_test: Etiquetas de prueba.

    Returns:
    - metricas: Un diccionario con las métricas evaluadas.
    """
    # Ajustar el modelo con los datos de entrenamiento
    modelo.fit(X_train, y_train)

    # Predecir en los datos de prueba
    y_pred = modelo.predict(X_test)

    # Calcular la matriz de confusión
    vp, fp, fn, vn = confusion_matrix(y_test, y_pred).ravel()

    # Calcular las curvas ROC y los valores de AUC
    fpr, tpr, _ = roc_curve(y_test, y_pred)
    auc_score = roc_auc_score(y_test, y_pred)

    # Calcular el accuracy score
    accuracy = accuracy_score(y_test, y_pred)

    # Calcular la precision
    precision = precision_score(y_test, y_pred, zero_division=0.0)

    # Calcular el ECM
    ecm = mean_squared_error(y_test, y_pred)

    # Crear una colección con las métricas evaluadas
    metricas = {
        "Verdaderos Positivos": vp,
        "Verdaderos Negativos": vn,
        "Falsos Positivos": fp,
        "Falsos Negativos": fn,
        "AUC": auc_score,
        "Accuracy": accuracy,
        "Precision": precision,
        "ECM": ecm,
    }
    return metricas

In [40]:
from sklearn.model_selection import KFold
import numpy as np


def cross_validation(modelo, k, X, y):
    """
    Realiza validación cruzada con k iteraciones y evalúa el modelo en cada iteración.

    Parameters:
    - modelo: Objeto del modelo a evaluar.
    - k: Número de iteraciones para cross validation.
    - X: Datos de entrada.
    - y: Etiquetas.

    Returns:
    - list: Lista de diccionarios con métricas para cada iteración.
    """
    kf = KFold(n_splits=k, shuffle=True)
    metricas_iteraciones = []

    for train_index, test_index in kf.split(X):
        X_train, X_test = X.iloc[train_index], X.iloc[test_index]
        y_train, y_test = y.iloc[train_index], y.iloc[test_index]

        metricas_iteracion = evalua_metodo(modelo, X_train, y_train, X_test, y_test)
        metricas_iteraciones.append(metricas_iteracion)

    return {
        key: np.mean(
            [metricas_iteracion[key] for metricas_iteracion in metricas_iteraciones]
        )
        for key in metricas_iteraciones[0].keys()
    }

In [103]:
def evalua_config(modelo, hiperparametros, X, y, k):
    """
    Evalúa diferentes configuraciones de hiperparámetros utilizando validación cruzada.

    Parameters:
    - modelo: Objeto del modelo a evaluar.
    - hiperparametros: Lista de configuraciones de hiperparámetros a probar.
    - X: Datos de entrada.
    - y: Etiquetas.
    - k: Número de iteraciones para cross validation.

    Returns:
    - dict: Configuración con menor error promedio.
    """
    error = []
    for config in hiperparametros:
        modelo.set_params(**config)
        metricas = cross_validation(modelo, k, X, y)
        error.append((config, metricas))
    try: 
        mejor_config = min(error, key=lambda x: x[1]['ECM'])
    except ValueError:
        metricas = cross_validation(modelo, k, X, y)
        mejor_config = {}, metricas
    return mejor_config

In [113]:
from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import (
    BaggingClassifier,
    RandomForestClassifier,
    GradientBoostingClassifier,
)
import pandas as pd


def evalua_multiples_metodos(hiperparametros, X, y, k=5):
    """
    Evalúa varios modelos con diferentes hiperparámetros y muestra los resultados.

    Parameters:
    - hiperparametros: Lista de configuraciones de hiperparámetros a probar.
    - X: Datos de entrada.
    - y: Etiquetas.
    - k: Número de iteraciones para validación cruzada. Por defecto, k=5.
    """
    df_dict = {}
    # Configurar modelos con hiperparámetros
    for nombre_modelo in [
        "LogisticRegression",
        "LinearDiscriminantAnalysis",
        "KNeighborsClassifier",
        "DecisionTreeClassifier",
        "BaggingClassifier",
        "RandomForestClassifier",
        "GradientBoostingClassifier",
    ]:
        modelo = eval(nombre_modelo)()
        config, metricas = evalua_config(
            modelo, hiperparametros.get(nombre_modelo, []), X, y, k
        )
        df_dict[nombre_modelo] = metricas
        df_dict[nombre_modelo]['Config'] = config
    return pd.DataFrame(df_dict).T

In [119]:
# EJEMPLO. NO PONER EN LA VERSION FINAL

hiperparametros = {
    'LogisticRegression': [{'C': x/10} for x in range(1, 100)],
}
X, y = respondieron[['IV6', 'IV8']], respondieron['pobre']

evalua_multiples_metodos(hiperparametros, X, y, k=5)

,Verdaderos Positivos,Verdaderos Negativos,Falsos Positivos,Falsos Negativos,AUC,Accuracy,Precision,ECM,Config
LogisticRegression,513.4,15.6,6.2,302.4,0.518631,0.631571,0.72199,0.368429,{'C': 1.3}
LinearDiscriminantAnalysis,513.4,15.0,6.2,303.0,0.517567,0.630848,0.709737,0.369152,{}
KNeighborsClassifier,516.6,5.2,3.0,312.8,0.505464,0.622982,0.473939,0.377018,{}
DecisionTreeClassifier,513.8,15.6,5.8,302.4,0.518966,0.632046,0.735319,0.367954,{}
BaggingClassifier,513.8,15.6,5.8,302.4,0.519033,0.632046,0.719399,0.367954,{}
RandomForestClassifier,513.4,15.6,6.2,302.4,0.518579,0.631566,0.718298,0.368434,{}
GradientBoostingClassifier,513.4,15.0,6.2,303.0,0.51749,0.630851,0.742604,0.369149,{}